name: HealthID - Frontend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install depencies
      run: |
        npm install 
    - name: Build and Test Project
      run: |
        npm run build 
        npm run test:coverage
      env:
        API_KEY: ${{ secrets.API_KEY }}
        APP_LINK: ${{ secrets.APP_LINK }}
        CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        UPLOAD_PRESET: ${{ secrets.UPLOAD_PRESET }}
